name: Refresh product versions

on:
  schedule:
    - cron: '47 4 * * *'
  workflow_dispatch:
  workflow_run:
    workflows: ["Build Updater"]
    types: [completed]

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: cachix/install-nix-action@v12
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Download updater
        uses: dawidd6/action-download-artifact@v2.13.0
        with:
          workflow: build-updater.yml
          name: jetbrains-updater

      - name: Run updater
        run: mkdir data && ./jetbrains-updater data/packages.json

      - name: Commit changes, if any
        uses: EndBug/add-and-commit@v7.1.0
        with:
          add: 'data'
          author_name: github-actions
          author_email: 41898282+github-actions[bot]@users.noreply.github.com
          message: 'Automatic package update'
